//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class collected_food_items
    {
        public int id { get; set; }
        public int collect_request_id { get; set; }
        public string name { get; set; }
        public int quantity { get; set; }
        public string condition { get; set; }
        public string distribution_status { get; set; }
        public Nullable<System.DateTime> distribution_completion_time { get; set; }
    
        public virtual collect_requests collect_requests { get; set; }
    }
}
