//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZeroHunger.Entity_Framework
{
    using System;
    using System.Collections.Generic;
    
    public partial class collect_requests
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public collect_requests()
        {
            this.collected_food_items = new HashSet<collected_food_items>();
        }
    
        public int id { get; set; }
        public int restaurant_id { get; set; }
        public Nullable<int> employee_id { get; set; }
        public System.DateTime time { get; set; }
        public System.DateTime maximum_preserve_time { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> completion_time { get; set; }
    
        public virtual employee employee { get; set; }
        public virtual restaurant restaurant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<collected_food_items> collected_food_items { get; set; }
    }
}
